/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CompA {
    }
    interface CompB {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCompAElement extends Components.CompA, HTMLStencilElement {
    }
    var HTMLCompAElement: {
        prototype: HTMLCompAElement;
        new (): HTMLCompAElement;
    };
    interface HTMLCompBElement extends Components.CompB, HTMLStencilElement {
    }
    var HTMLCompBElement: {
        prototype: HTMLCompBElement;
        new (): HTMLCompBElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "comp-a": HTMLCompAElement;
        "comp-b": HTMLCompBElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CompA {
    }
    interface CompB {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "comp-a": CompA;
        "comp-b": CompB;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "comp-a": LocalJSX.CompA & JSXBase.HTMLAttributes<HTMLCompAElement>;
            "comp-b": LocalJSX.CompB & JSXBase.HTMLAttributes<HTMLCompBElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
